Repository Flow-Launcher/docs, pull requests merged in 2021-03, with the labels that each got.

#8 d'oh wrong URL
  _sidebar.md
Labels: documentation

#9 Update _sidebar.md
  _sidebar.md
Labels: bug

#11 Update doc website title
  index.html
Labels: enhancement

#13 Update title name (#12)
  _coverpage.md
  index.html
Labels: bug

#14 Update typo
  Plugins.md
Labels: bug

#15 remove full stop
  port-plugins.md
Labels: bug
